---
- name: Install build dependencies
  xbps:
    pkg:
      - base-devel
      - libressl-devel
      - python-devel
      - python-pip
    state: present

- name: Install certbot
  pip:
    name: certbot
    state: present

- name: Check for certificate
  stat:
    path: "/etc/letsencrypt/live/{{ certbot_domain }}/fullchain.pem"
  register: certificate

- name: Run certbot
  command: "certbot certonly --non-interactive --agree-tos --email {{ certbot_contact_email }} --webroot -w {{ certbot_webroot }} -d {{ certbot_domain }}"
  when: not certificate.stat.exists

- name: Install certbot cron job
  copy:
    src: certbot.cron
    dest: /etc/cron.d/certbot
    owner: root
    group: root
    mode: 0644
